-- Create properties table
CREATE TABLE IF NOT EXISTS public.properties (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  price NUMERIC NOT NULL,
  listing_type TEXT NOT NULL CHECK (listing_type IN ('for_sale', 'for_rent')),
  category TEXT NOT NULL CHECK (category IN ('house', 'apartment', 'villa', 'penthouse')),
  address TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  state TEXT,
  country TEXT,
  location_formatted TEXT NOT NULL,
  bedrooms INTEGER NOT NULL DEFAULT 1,
  bathrooms NUMERIC(3, 1) NOT NULL DEFAULT 1.0,
  area_sq_meters NUMERIC NOT NULL DEFAULT 0,
  image_url TEXT NOT NULL,
  image_alt TEXT NOT NULL DEFAULT '',
  badge TEXT CHECK (badge IS NULL OR badge IN ('Exclusive', 'New Arrival', 'Featured')),
  is_featured BOOLEAN NOT NULL DEFAULT false,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_properties_slug ON public.properties (slug);
CREATE INDEX IF NOT EXISTS idx_properties_is_featured ON public.properties (is_featured);
CREATE INDEX IF NOT EXISTS idx_properties_listing_type ON public.properties (listing_type);
CREATE INDEX IF NOT EXISTS idx_properties_category ON public.properties (category);
CREATE INDEX IF NOT EXISTS idx_properties_created_at ON public.properties (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_properties_price ON public.properties (price);

-- Enable Row Level Security (RLS)
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- Allow public read access to all properties
DROP POLICY IF EXISTS "Allow public read access" ON public.properties;
CREATE POLICY "Allow public read access" ON public.properties
  FOR SELECT
  USING (true);

-- Allow anon insert/update for seeding and public development
DROP POLICY IF EXISTS "Allow anon insert" ON public.properties;
CREATE POLICY "Allow anon insert" ON public.properties
  FOR INSERT
  TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update" ON public.properties;
CREATE POLICY "Allow anon update" ON public.properties
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

-- Allow service_role and authenticated full access
DROP POLICY IF EXISTS "Allow service role full access" ON public.properties;
CREATE POLICY "Allow service role full access" ON public.properties
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Seed initial properties data
INSERT INTO public.properties (
  id, title, slug, price, listing_type, category, address, city, state, country,
  location_formatted, bedrooms, bathrooms, area_sq_meters, image_url, image_alt,
  badge, is_featured, description, created_at
) VALUES
-- Featured Properties
(
  'feat-1',
  'The Glass Pavilion',
  'the-glass-pavilion-beverly-hills',
  5250000,
  'for_sale',
  'villa',
  '1004 Benedict Canyon Dr',
  'Beverly Hills',
  'California',
  'USA',
  'Beverly Hills, California',
  5,
  4.5,
  4200,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCra-FKp81t0_OM8bWD55m2o9OOSnR_v7D0UilyExMImxyIcr9tIMZ2Py3HcC0ra_MtSsBkduMcwxUNKI9_iSXFFr_YRON1SF9hNM3fcYy-uG7N7uusL0Z367WINi1V7_GwfNQx-gsbUqLtzVi4ivFyqFQGb4qBs79bALeSFb6i3_ZnJnI1VVrN-VeZYHjfYyQI5C6zy90N3uxWZpwzIBhNoUDKKQjQ8EOEYPoyPTzhnh6b6AS3dkkFJ8t4xSDC6qjhMrQUoUPnAeM',
  'Luxury modern villa exterior with pool',
  'Exclusive',
  true,
  'An architectural masterpiece in Beverly Hills featuring floor-to-ceiling glass walls, infinity edge pool, and panoramic canyon vistas.',
  '2026-08-10T10:00:00Z'
),
(
  'feat-2',
  'Azure Heights Penthouse',
  'azure-heights-penthouse-vancouver',
  3800000,
  'for_sale',
  'penthouse',
  '888 Burrard Street, Penthouse 42',
  'Vancouver',
  'BC',
  'Canada',
  'Downtown, Vancouver',
  3,
  3.0,
  2100,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDurAGHzg_fpQxFal-obkFVy1Q3WLPdueAQpz0itcQiRV-WfvulnBEDJbNeV8J06q4mX7PTtXYVJjX4-mHVr_khZLZxQ_s8f6fruGqzeqALyMu8wEHRK1EsOs9f4_jPmS7FxcdzrDkR88Wz0GjaPLXkTZRoJQfur59rxYRLi-WYcW-VU_gKS39CPLOMlftvqGvW0IOk5tXgst5mJ4WQM-ICN4vkdel9ido9YFUQga0OI10i6NSe5W4owt33-2YRi_b_ltdZW2QZC5s',
  'Modern interior living room with view',
  'New Arrival',
  true,
  'Panoramic luxury penthouse offering 360-degree vistas of the mountains and ocean, private elevator access, and rooftop terrace.',
  '2026-08-14T08:30:00Z'
),
(
  'feat-3',
  'Villa Bellagio Lakefront',
  'villa-bellagio-lakefront-como',
  7800000,
  'for_sale',
  'villa',
  'Via Regina 45',
  'Bellagio',
  'Lombardy',
  'Italy',
  'Bellagio, Lake Como, Italy',
  6,
  7.0,
  680,
  'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
  'Grand Italian lakefront villa with manicured gardens',
  'Exclusive',
  true,
  'Historic neo-classical villa overlooking Lake Como with private boat dock, botanical gardens, and frescoed reception halls.',
  '2026-08-16T09:00:00Z'
),
(
  'feat-4',
  'Roppongi Sky Residence',
  'roppongi-sky-residence-tokyo',
  14500,
  'for_rent',
  'penthouse',
  '6-10-1 Roppongi',
  'Minato-ku',
  'Tokyo',
  'Japan',
  'Roppongi, Tokyo, Japan',
  3,
  3.5,
  280,
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
  'Ultra-luxury Tokyo penthouse with panoramic skyline view',
  'Featured',
  true,
  'Stunning high-floor luxury sanctuary commanding views of Tokyo Tower and Mount Fuji with dedicated concierge and Japanese zen tea garden.',
  '2026-08-16T14:30:00Z'
),
-- Market Properties
(
  'prop-1',
  'Modern Family Home',
  'modern-family-home-seattle',
  850000,
  'for_sale',
  'house',
  '123 Pine St',
  'Seattle',
  'Washington',
  'USA',
  '123 Pine St, Seattle',
  3,
  2.0,
  120,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDuQ9M7U6euA6_cXmYuXnej-N5IuawAW8ds-4G1mzfqmiBc13qXsPhf9_j_zTB8gfEunrBHo8xMsxYwCw_pl8fsxbxRkmyvLR1N9Tiye5ZJG7fwlLn9MwyBanXYhE0emGwp59es1FEyQTRQbmXLUKO74Yj34ZHqrqIkOtMKhP8CmRFvfoHT5LAe10105vUhKNkxIBvtt530nfLigSUTemOOcJMVNmsgactntRJUwOBU_TZzND7BYtDklr8uZcNYlQOK5U74-ufIf-E',
  'Modern white house facade',
  NULL,
  false,
  'Bright open-plan family home with contemporary Scandinavian finishes, private landscaped garden, and energy-efficient architecture.',
  '2026-08-12T14:20:00Z'
),
(
  'prop-2',
  'Urban Loft',
  'urban-loft-portland',
  3200,
  'for_rent',
  'apartment',
  '456 Elm Ave',
  'Portland',
  'Oregon',
  'USA',
  '456 Elm Ave, Portland',
  1,
  1.0,
  85,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuB4zNatD3vePhIZAi6OHHJKmamYSgeBNSKjEt32tvkkf4s6aBXCF8R4LNfDfPa9leA0t6N1OKOcP358WwZrnosbCBxSM7EaY2_P7qkx3MinRgmHQn7RvleNTwy8cLigMoR3iv0u83chBVbZYI6BcNMcqv80W-l1pIUgIWZcDIXEqtUatrsojSGfM0lTNDZpkBntBUkRY6NB4ZUymYNYvTHXKbO8NZ6N6uoyuuHqcaRWKzHCNXkOR3p-_EVFAHR8QwijIY_m1mefPZ4',
  'Stylish apartment living room',
  NULL,
  false,
  'Industrial-chic loft featuring 14-foot ceilings, exposed brick, chef kitchen, and oversized soundproof windows in the heart of the Pearl District.',
  '2026-08-13T11:15:00Z'
),
(
  'prop-3',
  'Highland Retreat',
  'highland-retreat-bend',
  620000,
  'for_sale',
  'house',
  '789 Mountain Rd',
  'Bend',
  'Oregon',
  'USA',
  '789 Mountain Rd, Bend',
  2,
  2.0,
  98,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuARQWC19e7mleUpjb8CWLztEv_svJeRFOaC2i-9r9GctFuX5Barzhfai9wNM1WW8bcGlqdFM32d3KPf7SItom5ijdHOz5rGGQPeT7PlWs8-y9LkfcsHLQqsLxalhxP94XJo76_mAMp7T2dVj3hPKHNzTDLLiS6ujSdSsyo3onxQthp4ZkVE8op92gyTLUUucaGaxO8vJvyhH3HuWB07EPqT1WsW0lr9Of5lUPonjG9eiqE1XiJXTqzXUZQt5JorfPwCO1MioZA_Zro',
  'Cabin in the woods exterior',
  NULL,
  false,
  'Serene mountain residence nestled amidst towering pines with cedar wood accents, stone fireplace, and wrap-around deck.',
  '2026-08-11T09:40:00Z'
),
(
  'prop-4',
  'Sea View Penthouse',
  'sea-view-penthouse-miami',
  4500,
  'for_rent',
  'penthouse',
  '321 Ocean Dr',
  'Miami',
  'Florida',
  'USA',
  '321 Ocean Dr, Miami',
  3,
  3.0,
  180,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBGq4Phm0uDzCnjHAsnWpYTBVpOds_M6iOsJuRQQA5eUZHkztGgtc7eh_OE6wBeyW1-iZh7yyhROnvvmqkAZ9tyAWFGXk0FG52zU4kZ_EDLA0U0cRszy7byNXTeWe0_hS53SYmtCTEV8Y1AM-WxiIC38UMa15QwFDjXtCGQOxoh35K0Ol_70vfsxm0VqDbaWkr8tcEbLTLy0NXH_GcpGK4lAXizgxYOIlFWGyau-4OIfPZRpjCBDbz_qu3VlN201UUJGiuM9ajVd-U',
  'Bright bedroom with large window overlooking ocean',
  NULL,
  false,
  'High-floor beachfront residence with sweeping Atlantic views, private balcony, marble bathrooms, and full concierge building service.',
  '2026-08-15T16:50:00Z'
),
(
  'prop-5',
  'Central Studio',
  'central-studio-chicago',
  550000,
  'for_sale',
  'apartment',
  '555 Main St',
  'Chicago',
  'Illinois',
  'USA',
  '555 Main St, Chicago',
  1,
  1.0,
  50,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuA1w-Hb1289NqZKon3VK8bpmMiCDYYiAMT5egzTINo9m9wSZRHv-k-1IGTVoL1NT8YeZXJHa87JPNDIPrtrbP7jChHq0ypXF90uByhC6VA9O788_B4FY8JVg4chbWN9bcrn9-9FvVvfZX8Aj60Iqg_C8CsCA9DEnJqi2rJvzmK5UP5z-9XRTRjBneAPCa8iGgGWBD9yYKsziN6vn0ePBDGo3inieQtmbr46W31p6UfQ649XRxTm7ygOY2J-jxW1r0qWs8i97KGpkTE',
  'Cozy apartment interior',
  NULL,
  false,
  'Smartly designed downtown apartment steps from shopping, dining, and cultural arts center with designer finishes and luxury building amenities.',
  '2026-08-09T18:00:00Z'
),
(
  'prop-6',
  'Garden Villa',
  'garden-villa-austin',
  2800,
  'for_rent',
  'villa',
  '999 Oak Ln',
  'Austin',
  'Texas',
  'USA',
  '999 Oak Ln, Austin',
  2,
  2.0,
  110,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCfGXdY0g51ojSg0GMeTW9ndLY3mpKK3oMtWxo2nwd_dwi1pgn1Boi_ovaDGIFhUA7nwu3WdBch8ZuHxoHu3QfgM5ceAsp8pglRVyCROWNcy9zeDNP2wqLoevyKGcaEyFYHYpIx2KK46nLWthnHiHugmkKw48kJsL8IjMO1bL3T1Zwt8bvQDTTUHTgB3GqZ2RU2asRzF1jVg0rLw3LWXXTq0YF1CsbhlWpYOuCEpH5bB8zkBlbKXR4At_M46AL8rJqn5c6BrPD5PP8',
  'Modern minimalist home exterior',
  NULL,
  false,
  'Contemporary single-story sanctuary surrounded by tranquil gardens, offering private outdoor lounge, quartz kitchen, and serene master retreat.',
  '2026-08-14T12:10:00Z'
),
(
  'prop-7',
  'Skyline Terrace Residence',
  'skyline-terrace-residence-new-york',
  1250000,
  'for_sale',
  'apartment',
  '72 Wall St',
  'New York',
  'New York',
  'USA',
  '72 Wall St, New York',
  2,
  2.0,
  135,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDurAGHzg_fpQxFal-obkFVy1Q3WLPdueAQpz0itcQiRV-WfvulnBEDJbNeV8J06q4mX7PTtXYVJjX4-mHVr_khZLZxQ_s8f6fruGqzeqALyMu8wEHRK1EsOs9f4_jPmS7FxcdzrDkR88Wz0GjaPLXkTZRoJQfur59rxYRLi-WYcW-VU_gKS39CPLOMlftvqGvW0IOk5tXgst5mJ4WQM-ICN4vkdel9ido9YFUQga0OI10i6NSe5W4owt33-2YRi_b_ltdZW2QZC5s',
  'Luxury skyline residence interior with view',
  NULL,
  false,
  'Refined corner apartment with oversized windows, custom millwork, spa-inspired bathrooms, and prestigious Manhattan skyline views.',
  '2026-08-08T15:30:00Z'
),
(
  'prop-8',
  'Palisades Modernist Villa',
  'palisades-modernist-villa-los-angeles',
  6800,
  'for_rent',
  'villa',
  '1420 Pacific Coast Hwy',
  'Pacific Palisades',
  'California',
  'USA',
  'Pacific Palisades, California',
  4,
  4.5,
  310,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCra-FKp81t0_OM8bWD55m2o9OOSnR_v7D0UilyExMImxyIcr9tIMZ2Py3HcC0ra_MtSsBkduMcwxUNKI9_iSXFFr_YRON1SF9hNM3fcYy-uG7N7uusL0Z367WINi1V7_GwfNQx-gsbUqLtzVi4ivFyqFQGb4qBs79bALeSFb6i3_ZnJnI1VVrN-VeZYHjfYyQI5C6zy90N3uxWZpwzIBhNoUDKKQjQ8EOEYPoyPTzhnh6b6AS3dkkFJ8t4xSDC6qjhMrQUoUPnAeM',
  'Modernist villa with pool',
  NULL,
  false,
  'Private gated modernist sanctuary with seamless indoor-outdoor living, sparkling pool, wine room, and breathtaking Pacific sunsets.',
  '2026-08-07T11:00:00Z'
),
(
  'prop-9',
  'Aspen Alpine Sanctuary',
  'aspen-alpine-sanctuary-colorado',
  4200000,
  'for_sale',
  'house',
  '520 Red Mountain Rd',
  'Aspen',
  'Colorado',
  'USA',
  '520 Red Mountain Rd, Aspen',
  4,
  4.0,
  390,
  'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
  'Modern alpine luxury chalet',
  NULL,
  false,
  'Ski-in, ski-out timber and stone mountain lodge with heated outdoor spa, vaulted timber beams, and dramatic valley views.',
  '2026-08-16T12:00:00Z'
),
(
  'prop-10',
  'Mayfair Heritage Suite',
  'mayfair-heritage-suite-london',
  8200,
  'for_rent',
  'apartment',
  '18 Grosvenor Square',
  'London',
  'England',
  'UK',
  'Mayfair, London, UK',
  2,
  2.0,
  140,
  'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
  'Stately Mayfair apartment living room',
  NULL,
  false,
  'Elegant Georgian mansion apartment in prestigious Mayfair featuring bespoke joinery, Chevron oak floors, and 24-hour porterage.',
  '2026-08-15T10:20:00Z'
),
(
  'prop-11',
  'Côte d''Azur Cliffside Estate',
  'cote-dazur-cliffside-estate-cannes',
  9500000,
  'for_sale',
  'villa',
  'Boulevard de la Croisette',
  'Cannes',
  'Provence-Alpes-Côte d''Azur',
  'France',
  'Cannes, French Riviera, France',
  5,
  6.0,
  550,
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
  'French Riviera cliffside villa with infinity pool',
  NULL,
  false,
  'Unrivaled Mediterranean estate with cliff-edge infinity pool, expansive limestone terraces, and direct private access to turquoise cove.',
  '2026-08-14T17:40:00Z'
),
(
  'prop-12',
  'Malibu Coastline Penthouse',
  'malibu-coastline-penthouse-california',
  12000,
  'for_rent',
  'penthouse',
  '22000 Pacific Coast Hwy',
  'Malibu',
  'California',
  'USA',
  'Malibu, California, USA',
  3,
  3.0,
  240,
  'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
  'Sunlit oceanfront Malibu penthouse with deck',
  NULL,
  false,
  'Breathtaking beachfront residence hovering directly over the Pacific waves, complete with teak wraparound deck and sunset dining pavilion.',
  '2026-08-14T09:15:00Z'
),
(
  'prop-13',
  'Tulum Eco-Chic Villa',
  'tulum-eco-chic-villa-mexico',
  5400,
  'for_rent',
  'villa',
  'Carretera Tulum-Boca Paila',
  'Tulum',
  'Quintana Roo',
  'Mexico',
  'Tulum, Quintana Roo, Mexico',
  3,
  3.5,
  260,
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  'Tropical luxury villa immersed in Mayan jungle',
  NULL,
  false,
  'Organic modern villa blending polished chukum plaster, indigenous hardwoods, private cenote-style plunge pool, and rooftop stargazing deck.',
  '2026-08-13T15:00:00Z'
),
(
  'prop-14',
  'Le Marais Parisian Duplex',
  'le-marais-parisian-duplex-france',
  2100000,
  'for_sale',
  'apartment',
  'Rue des Francs-Bourgeois',
  'Paris',
  'Île-de-France',
  'France',
  'Le Marais, Paris, France',
  2,
  2.0,
  115,
  'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
  'Light-filled Parisian duplex interior with historic mouldings',
  NULL,
  false,
  'Charm-filled 17th-century duplex featuring original exposed oak beams, marble fireplaces, bespoke kitchen, and quiet courtyard views.',
  '2026-08-12T11:30:00Z'
),
(
  'prop-15',
  'Wailea Oceanfront Villa',
  'wailea-oceanfront-villa-maui',
  6900000,
  'for_sale',
  'house',
  '3850 Wailea Alanui Dr',
  'Wailea',
  'Hawaii',
  'USA',
  'Wailea, Maui, Hawaii',
  4,
  4.5,
  430,
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
  'Luxurious Hawaiian contemporary residence overlooking ocean',
  NULL,
  false,
  'Seamless indoor-outdoor island living with vanishing pocket doors, private lagoon pool, lush tropical landscaping, and whale watching views.',
  '2026-08-11T13:45:00Z'
),
(
  'prop-16',
  'Lake Zurich Panorama Loft',
  'lake-zurich-panorama-loft-switzerland',
  7500,
  'for_rent',
  'penthouse',
  'Seestrasse 108',
  'Zurich',
  'Zurich',
  'Switzerland',
  'Zurich, Switzerland',
  2,
  2.5,
  175,
  'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
  'Swiss minimalist luxury penthouse with lake and Alps views',
  NULL,
  false,
  'Ultra-sleek Swiss architectural masterpiece with floor-to-ceiling glass, private elevator, automated climate control, and alpine lake vistas.',
  '2026-08-10T16:20:00Z'
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  price = EXCLUDED.price,
  listing_type = EXCLUDED.listing_type,
  category = EXCLUDED.category,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  country = EXCLUDED.country,
  location_formatted = EXCLUDED.location_formatted,
  bedrooms = EXCLUDED.bedrooms,
  bathrooms = EXCLUDED.bathrooms,
  area_sq_meters = EXCLUDED.area_sq_meters,
  image_url = EXCLUDED.image_url,
  image_alt = EXCLUDED.image_alt,
  badge = EXCLUDED.badge,
  is_featured = EXCLUDED.is_featured,
  description = EXCLUDED.description,
  created_at = EXCLUDED.created_at;
